#!/usr/bin/env python3
"""
Renders the JSON written by `z30 --benchmark suite` as markdown tables.

    python research/summarize_suite.py research/results/<commit>          # print
    python research/summarize_suite.py research/results/<commit> --write  # also write SUMMARY.md there

Standard library only. It reads the result files and formats them; it computes nothing that is
not in them except percentages and the 50% crossings already present. The documentation's tables
are pasted from this output, so a figure in docs/ or wiki/ can be traced to a result file
without anyone having retyped it.
"""

import json
import os
import sys


def load(directory, name):
    path = os.path.join(directory, name + ".json")
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def num(v, spec):
    """Formats a number, or 'n/a' where the result file holds null (NaN: nothing to measure)."""
    return "n/a" if v is None else format(v, spec)


def pct(p):
    lo, hi = p["wilson95"]
    return f"{p['decoded']}/{p['frames']} = {p['percent']:.1f}% [{lo:.1f}, {hi:.1f}]"


def rate_table(doc, header):
    lines = [f"| {header} | Decoded (Wilson 95%) | False | Dups dropped / emitted | Latency p50 / max (ms) |",
             "| :--- | :--- | ---: | :---: | :---: |"]
    for p in doc["points"]:
        lat = p["latency_ms"]
        lines.append(
            f"| {p['label']} | {pct(p)} | {p['false_decodes']} | {p['duplicates_dropped']} / {p['duplicates_emitted']} "
            f"| {num(lat['p50'], '.0f')} / {num(lat['max'], '.0f')} |"
        )
    return "\n".join(lines)


def crossing(c):
    if not c:
        return "not bracketed by the measured points"
    lo, hi = c["interval"]
    fmt = lambda v: "n/a" if v is None else f"{v:.2f}"  # noqa: E731
    return f"{c['at']:.2f} dB [{fmt(lo)}, {fmt(hi)}]"


def provenance(doc):
    p = doc["provenance"]
    return (f"commit `{p['git_commit']}`, {p['build_profile']} build, {p['rustc']}, {p['target']}, "
            f"{p['cpu']} ({p['logical_cpus']} logical CPUs), started {p['started_utc']}, "
            f"{p['elapsed_s']:.0f} s; seed {doc['seed']['suite_seed']}")


def main():
    directory = sys.argv[1]
    out = []
    add = out.append
    add(f"# Benchmark suite results: `{os.path.basename(os.path.normpath(directory))}`\n")
    add("Generated by `research/summarize_suite.py` from the JSON in this directory. Software "
        "simulation through the production receiver `decode_slot`; no hardware involved.\n")

    doc = load(directory, "awgn")
    if doc:
        add("## AWGN, single station, blind acquisition\n")
        add(provenance(doc) + ".\n")
        add(f"Placement: {json.dumps(doc['placement'])}. {doc['frames_per_point']} frames per point.\n")
        add(rate_table(doc, "SNR (2500 Hz)"))
        add(f"\n50% crossing: **{crossing(doc['crossing_50pct_db'])}**; "
            f"90% crossing: **{crossing(doc['crossing_90pct_db'])}**.\n")

    doc = load(directory, "snr")
    if doc:
        add("## Reported SNR, DT and frequency against the truth\n")
        add(provenance(doc) + f". {doc['frames_per_point']} frames per point; validated range "
            f"{doc['validated_range_db'][0]:+.0f} to {doc['validated_range_db'][1]:+.0f} dB.\n")
        add("| True SNR | Decoded | SNR bias / sd (dB) | SNR error min / max (dB) | DT bias / sd (ms) | f bias / sd (Hz) |")
        add("| ---: | :--- | :---: | :---: | :---: | :---: |")
        for p in doc["points"]:
            s, d, f = p["snr_measured"], p["dt_error_ms"], p["freq_error_hz"]
            add(f"| {p['param']:+.0f} dB | {p['decoded']}/{p['frames']} | {num(s['bias_db'], '+.2f')} / {num(s['sd_db'], '.2f')} "
                f"| {num(s['min_error_db'], '+.2f')} / {num(s['max_error_db'], '+.2f')} | {num(d['bias'], '+.2f')} / {num(d['sd'], '.2f')} "
                f"| {num(f['bias'], '+.3f')} / {num(f['sd'], '.3f')} |")
        add("")

    for name, header, title in [
        ("drift", "Condition", "Linear drift across the frame"),
        ("timing", "DT", "Timing offset (DT)"),
        ("clock", "Receiver sample-clock error", "Sound-card clock error"),
        ("impair", "Impairment", "Audio impairments"),
        ("busy", "Band", "Busy band, random overlapping placement"),
    ]:
        doc = load(directory, name)
        if doc:
            add(f"## {title}\n")
            add(provenance(doc) + ".\n")
            add(rate_table(doc, header))
            add("")

    doc = load(directory, "false")
    if doc:
        add("## False decodes (no z-30 frame present)\n")
        add(provenance(doc) + ".\n")
        add("| Content | Slots | False decodes | LDPC attempts | 95% upper bound per slot |")
        add("| :--- | ---: | ---: | ---: | ---: |")
        for p in doc["points"]:
            add(f"| {p['label']} | {p['slots']} | {p['false_decodes']} | {p['ldpc_attempts']} | {p['upper95_per_slot']:.2e} |")
        pooled = doc["pooled"]
        add(f"| **Pooled** | {pooled['slots']} | {pooled['false_decodes']} | | {pooled['upper95_per_slot']:.2e} |\n")

    doc = load(directory, "sic")
    if doc:
        add("## Two-station collisions, SIC on versus off (paired)\n")
        add(provenance(doc) + f". {doc['trials_per_cell']} trials per cell; weak station at "
            f"{doc['points'][0]['param']['weak_snr_db']:+.0f} dB.\n")
        add("| dP (dB) | df (Hz) | dDT (s) | Strong decoded | Weak with SIC | Weak without SIC | Discordant (SIC only : single only) | McNemar p | False |")
        add("| ---: | ---: | ---: | :---: | :--- | :--- | :---: | ---: | ---: |")
        for p in doc["points"]:
            q = p["param"]
            n = p["trials"]
            add(f"| {q['power_difference_db']:.0f} | {q['frequency_separation_hz']:.0f} | {q['timing_separation_s']:.1f} "
                f"| {p['strong_decoded_with_sic']}/{n} | {p['weak_decoded_with_sic']}/{n} | {p['weak_decoded_without_sic']}/{n} "
                f"| {p['discordant_sic_only']} : {p['discordant_single_pass_only']} | {p['mcnemar_exact_p']:.1e} | {p['false_decodes']} |")
        add("")

    doc = load(directory, "fading")
    if doc:
        add("## Watterson fading (ensemble-normalised), average SNR\n")
        add(provenance(doc) + ".\n")
        add(rate_table(doc, "Preset, SNR"))
        add("")
        add("| Preset | Delay / Doppler | 50% crossing |")
        add("| :--- | :--- | :--- |")
        for name, v in doc["presets"].items():
            add(f"| {name} | {v['delay_ms']} ms / {v['doppler_hz']} Hz | {crossing(v['crossing_50pct_db'])} |")
        add("")

    text = "\n".join(out)
    print(text)
    if "--write" in sys.argv:
        with open(os.path.join(directory, "SUMMARY.md"), "w", encoding="utf-8") as handle:
            handle.write(text + "\n")


if __name__ == "__main__":
    main()
