#!/usr/bin/env python3
"""
Renders the JSON written by `z30 --benchmark suite` as markdown tables.

    python research/summarize_suite.py research/results/<commit>            # print
    python research/summarize_suite.py research/results/<commit> --write    # also write SUMMARY.md there
    python research/summarize_suite.py <dir> --partial                      # a directory without all ten

Standard library only. It reads the result files and formats them; it computes nothing that is
not in them except percentages and the 50% crossings already present. The documentation's tables
are pasted from this output, so a figure in docs/ or wiki/ can be traced to a result file
without anyone having retyped it.

It fails closed (exit 2, with the reason): a directory missing any of the ten benchmarks, or
whose files are not from one run (commit, seed, replicate, status, build profile, instrument),
is refused rather than summarised as if it were complete. A result that is not the published
run - a replicate, an exploratory size, a dirty build, or a run written elsewhere - is
summarised under a banner that says so; the first replicate run produced an ordinary-looking
table headed only by a 15-digit seed (audit 2026-09-28 RES-04 / RES-10).
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from suite_results import ResultError, load_set, status_of, status_line  # noqa: E402

DOCS = {}


def load(directory, name):
    """The result of `name` from the checked set loaded in main (None if absent with --partial)."""
    return DOCS.get(name)


def num(v, spec):
    """Formats a number, or 'n/a' where the result file holds null (NaN: nothing to measure)."""
    return "n/a" if v is None else format(v, spec)


def pct(p):
    lo, hi = p["wilson95"]
    return f"{p['decoded']}/{p['frames']} = {p['percent']:.1f}% [{lo:.1f}, {hi:.1f}]"


def rate_table(doc, header):
    lines = [f"| {header} | Decoded (Wilson 95%) | False | Dups dropped / emitted | Latency p50 / max (ms) |",
             "| :--- | :--- | ---: | :---: | :---: |"]
    for p in doc["points"]:
        lat = p["latency_ms"]
        lines.append(
            f"| {p['label']} | {pct(p)} | {p['false_decodes']} | {p['duplicates_dropped']} / {p['duplicates_emitted']} "
            f"| {num(lat['p50'], '.0f')} / {num(lat['max'], '.0f')} |"
        )
    return "\n".join(lines)


def crossing(c):
    if not c:
        return "not bracketed by the measured points"
    lo, hi = c["interval"]
    fmt = lambda v: "n/a" if v is None else f"{v:.2f}"  # noqa: E731
    return f"{c['at']:.2f} dB [{fmt(lo)}, {fmt(hi)}]"


def provenance(doc):
    p = doc["provenance"]
    text = (f"commit `{p['git_commit']}`, {p['build_profile']} build, {p['rustc']}, {p['target']}, "
            f"{p['cpu']} ({p['logical_cpus']} logical CPUs), started {p['started_utc']}, "
            f"{p['elapsed_s']:.0f} s; seed {doc['seed']['suite_seed']}")
    # Results written since 2026-09-28 also name their instrument and machine; older ones render
    # exactly as they always did, so a published SUMMARY.md still regenerates byte for byte.
    if "instrument" in p:
        isa = p.get("isa_features_detected")
        isa = ", ".join(k for k, v in isa.items() if v) if isinstance(isa, dict) else isa
        text += (f"; instrument sha256 `{p['instrument']['sha256'][:12]}`, Cargo.lock sha256 "
                 f"`{p.get('cargo_lock_sha256', 'n/a')[:12]}`, RUSTFLAGS `{p.get('rustflags') or 'none'}`, "
                 f"ISA features detected: {isa or 'none'}")
    if doc.get("status") is not None:
        text += f"; status **{doc['status']}**"
    return text


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    directory = args[0]
    try:
        docs, missing = load_set(directory, allow_partial="--partial" in sys.argv)
    except (ResultError, OSError) as e:
        print(f"summarize_suite.py: refused: {e}", file=sys.stderr)
        sys.exit(2)
    DOCS.clear()
    DOCS.update(docs)
    out = []
    add = out.append
    add(f"# Benchmark suite results: `{os.path.basename(os.path.normpath(directory))}`\n")
    add("Generated by `research/summarize_suite.py` from the JSON in this directory. Software "
        "simulation through the production receiver `decode_slot`; no hardware involved.\n")
    unpublished = [d for d in docs.values() if status_of(d) != "published"]
    if unpublished or missing:
        add("> **NOT THE PUBLISHED RUN.** These results must not be quoted as z-30's published figures.")
        for d in unpublished:
            add(f"> - {status_line(d)}")
        if missing:
            add(f"> - PARTIAL: {', '.join(missing)} not in this directory")
        add("")

    doc = load(directory, "awgn")
    if doc:
        add("## AWGN, single station, blind acquisition\n")
        add(provenance(doc) + ".\n")
        add(f"Placement: {json.dumps(doc['placement'])}. {doc['frames_per_point']} frames per point.\n")
        add(rate_table(doc, "SNR (2500 Hz)"))
        add(f"\n50% crossing: **{crossing(doc['crossing_50pct_db'])}**; "
            f"90% crossing: **{crossing(doc['crossing_90pct_db'])}**.\n")

    doc = load(directory, "snr")
    if doc:
        add("## Reported SNR, DT and frequency against the truth\n")
        add(provenance(doc) + f". {doc['frames_per_point']} frames per point; validated range "
            f"{doc['validated_range_db'][0]:+.0f} to {doc['validated_range_db'][1]:+.0f} dB.\n")
        add("| True SNR | Decoded | SNR bias / sd (dB) | SNR error min / max (dB) | DT bias / sd (ms) | f bias / sd (Hz) |")
        add("| ---: | :--- | :---: | :---: | :---: | :---: |")
        for p in doc["points"]:
            s, d, f = p["snr_measured"], p["dt_error_ms"], p["freq_error_hz"]
            add(f"| {p['param']:+.0f} dB | {p['decoded']}/{p['frames']} | {num(s['bias_db'], '+.2f')} / {num(s['sd_db'], '.2f')} "
                f"| {num(s['min_error_db'], '+.2f')} / {num(s['max_error_db'], '+.2f')} | {num(d['bias'], '+.2f')} / {num(d['sd'], '.2f')} "
                f"| {num(f['bias'], '+.3f')} / {num(f['sd'], '.3f')} |")
        add("")

    for name, header, title in [
        ("drift", "Condition", "Linear drift across the frame"),
        ("timing", "DT", "Timing offset (DT)"),
        ("clock", "Receiver sample-clock error", "Sound-card clock error"),
        ("impair", "Impairment", "Audio impairments"),
        ("busy", "Band", "Busy band, random overlapping placement"),
    ]:
        doc = load(directory, name)
        if doc:
            add(f"## {title}\n")
            add(provenance(doc) + ".\n")
            add(rate_table(doc, header))
            add("")

    doc = load(directory, "false")
    if doc:
        add("## False decodes (no z-30 frame present)\n")
        add(provenance(doc) + ".\n")
        add("| Content | Slots | False decodes | LDPC attempts | 95% upper bound per slot |")
        add("| :--- | ---: | ---: | ---: | ---: |")
        for p in doc["points"]:
            add(f"| {p['label']} | {p['slots']} | {p['false_decodes']} | {p['ldpc_attempts']} | {p['upper95_per_slot']:.2e} |")
        pooled = doc["pooled"]
        add(f"| **Pooled** | {pooled['slots']} | {pooled['false_decodes']} | | {pooled['upper95_per_slot']:.2e} |\n")

    doc = load(directory, "sic")
    if doc:
        add("## Two-station collisions, SIC on versus off (paired)\n")
        add(provenance(doc) + f". {doc['trials_per_cell']} trials per cell; weak station at "
            f"{doc['points'][0]['param']['weak_snr_db']:+.0f} dB.\n")
        add("| dP (dB) | df (Hz) | dDT (s) | Strong decoded | Weak with SIC | Weak without SIC | Discordant (SIC only : single only) | McNemar p | False |")
        add("| ---: | ---: | ---: | :---: | :--- | :--- | :---: | ---: | ---: |")
        for p in doc["points"]:
            q = p["param"]
            n = p["trials"]
            add(f"| {q['power_difference_db']:.0f} | {q['frequency_separation_hz']:.0f} | {q['timing_separation_s']:.1f} "
                f"| {p['strong_decoded_with_sic']}/{n} | {p['weak_decoded_with_sic']}/{n} | {p['weak_decoded_without_sic']}/{n} "
                f"| {p['discordant_sic_only']} : {p['discordant_single_pass_only']} | {p['mcnemar_exact_p']:.1e} | {p['false_decodes']} |")
        add("")

    doc = load(directory, "fading")
    if doc:
        add("## Watterson fading (ensemble-normalised), average SNR\n")
        if "doppler_definition" in doc:
            add(f"Doppler spread: {doc['doppler_definition']}.\n")
        add(provenance(doc) + ".\n")
        add(rate_table(doc, "Preset, SNR"))
        add("")
        add("| Preset | Delay / Doppler spread (2 sigma) | 50% crossing |")
        add("| :--- | :--- | :--- |")
        for name, v in doc["presets"].items():
            add(f"| {name} | {v['delay_ms']} ms / {v['doppler_hz']} Hz | {crossing(v['crossing_50pct_db'])} |")
        add("")

    text = "\n".join(out)
    print(text)
    if "--write" in sys.argv:
        with open(os.path.join(directory, "SUMMARY.md"), "w", encoding="utf-8") as handle:
            handle.write(text + "\n")


if __name__ == "__main__":
    main()
