//! z30-protocol against the frozen oracle (fixtures/golden, generated by reference/golden).

use serde_json::Value;
use std::path::PathBuf;
use z30_protocol::codec::{unpack_call_value, unpack_info, CallField, Callsign, Message};
use z30_protocol::crc::crc14;
use z30_protocol::gfsk::{frequency_pulse, Modulator};
use z30_protocol::ldpc::encode_payload;
use z30_protocol::symbols::codeword_to_symbols;

fn golden(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/golden").join(name)
}

fn load(name: &str) -> Value {
    serde_json::from_str(&std::fs::read_to_string(golden(name)).expect(name)).unwrap()
}

fn bits(s: &str) -> Vec<u8> {
    s.bytes().map(|b| b - b'0').collect()
}

fn read_f32(name: &str) -> Vec<f32> {
    std::fs::read(golden(name)).unwrap().chunks_exact(4).map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]])).collect()
}

#[test]
fn crc_ldpc_and_symbols_are_bit_exact() {
    let doc = load("codec.json");
    let vectors = doc["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 60);
    for v in vectors {
        let payload = bits(v["payload"].as_str().unwrap());
        assert_eq!(crc14(&payload) as u64, v["crc14"].as_u64().unwrap());
        let cw = encode_payload(&payload);
        assert_eq!(cw.to_vec(), bits(v["codeword"].as_str().unwrap()));
        let syms: Vec<u64> = codeword_to_symbols(&cw).iter().map(|&s| s as u64).collect();
        let want: Vec<u64> = v["symbols"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap()).collect();
        assert_eq!(syms, want);
    }
}

#[test]
fn callsign_field_matches_the_oracle_where_it_round_trips_and_refuses_where_it_does_not() {
    let doc = load("callsigns.json");
    let mut accepted = 0;
    for v in doc["vectors"].as_array().unwrap() {
        let call = v["call"].as_str().unwrap();
        let packed = v["packed"].as_u64().unwrap() as u32;
        let oracle_round_trips = v["round_trips"].as_bool().unwrap();
        match call {
            "CQ" | "CQ DX" | "CQ TEST" | "QRZ" => {
                assert_eq!(unpack_call_value(packed).to_string(), call);
                continue;
            }
            _ => {}
        }
        match Callsign::new(call) {
            Ok(c) => {
                accepted += 1;
                assert!(oracle_round_trips, "{call}: vNext accepts a call the oracle cannot round-trip");
                assert_eq!(c.packed(), packed, "{call}: packed value differs from the oracle");
                assert_eq!(unpack_call_value(packed), CallField::Call(c));
            }
            Err(e) => {
                // The oracle's round-trip test also rejects the placeholder and empty strings.
                assert!(!oracle_round_trips, "{call}: vNext refuses a call the oracle round-trips ({e})");
                // What the oracle would have transmitted is never shown as a callsign unless it
                // happens to be the canonical encoding of one - which is exactly C5.
                if let CallField::Call(other) = unpack_call_value(packed) {
                    assert_ne!(other.as_str(), call);
                }
            }
        }
    }
    assert!(accepted > 150);
}

#[test]
fn whole_messages_match_the_shipped_packer_or_are_refused() {
    let doc = load("messages.json");
    for m in doc["messages"].as_array().unwrap() {
        let text = m["text"].as_str().unwrap();
        let info = bits(m["info_bits"].as_str().unwrap());
        // The shipped packer's text round trip is textual ("+05" displays as "+5"); compare the
        // decoded message instead, which is what reached the air.
        let shipped = unpack_info(&info).expect("the shipped packer always wrote a valid CRC");
        match Message::parse(text) {
            Ok(msg) => {
                let enc = msg.encode().unwrap();
                assert_eq!(enc.info.to_vec(), info, "{text}: info bits differ from the shipped packer");
                assert_eq!(enc.codeword.to_vec(), bits(m["coded_bits"].as_str().unwrap()));
                let syms: Vec<u64> = enc.symbols.iter().map(|&s| s as u64).collect();
                let want: Vec<u64> = m["symbols"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap()).collect();
                assert_eq!(syms, want, "{text}");
                assert_eq!(shipped.to_message().as_ref(), Some(&msg), "{text}");
            }
            Err(e) => {
                // Refused: the shipped packer must have sent something other than what was typed.
                let typed = text.trim().to_uppercase();
                let sent = shipped.to_string();
                assert_ne!(sent, typed, "{text}: refused ({e}) although the shipped packer carried it");
                assert!(
                    !m["round_trips"].as_bool().unwrap() || text.contains("R-") || text.contains("R+"),
                    "{text}: refused ({e}) although the shipped codec round-trips it"
                );
            }
        }
    }
}

#[test]
fn grid_table_matches_the_shipped_decoder() {
    let doc = load("messages.json");
    for g in doc["decode_grid"].as_array().unwrap() {
        let code = g["code"].as_u64().unwrap() as u8;
        if (64..127).contains(&code) {
            assert_eq!(z30_protocol::codec::Extra::from_code(code).to_string(), g["grid"].as_str().unwrap());
        }
    }
}

#[test]
fn gfsk_pulse_and_waveforms_match_within_tolerance() {
    let doc = load("waveform.json");
    let pulse = frequency_pulse(2.0, 32);
    for (a, b) in pulse.iter().zip(doc["gfsk_pulse_bt2_nsps32"].as_array().unwrap()) {
        assert!((a - b.as_f64().unwrap()).abs() < 1e-15);
    }
    for f in doc["frames"].as_array().unwrap() {
        let fs = f["sample_rate_hz"].as_f64().unwrap();
        let f0 = f["base_freq_hz"].as_f64().unwrap();
        let stride = f["stride"].as_u64().unwrap() as usize;
        let mut symbols = [0u8; 75];
        for (i, s) in f["symbols"].as_array().unwrap().iter().enumerate() {
            symbols[i] = s.as_u64().unwrap() as u8;
        }
        let ours = Modulator::new(fs).unwrap().synthesize(&symbols, f0).unwrap();
        assert_eq!(ours.len() as u64, f["total_samples"].as_u64().unwrap());
        let theirs = read_f32(f["file"].as_str().unwrap());
        let mut worst = 0.0f32;
        for (i, t) in theirs.iter().enumerate() {
            worst = worst.max((ours[i * stride] - t).abs());
        }
        assert!(worst <= 1e-6, "{fs} Hz @ {f0} Hz: max |diff| {worst:e}");
    }
}
